export {};
console.log("hello from ts");
var myString;
var myNum;
var myBool;
myString = "333";
myNum = 22;
myBool = true;
// let strArr: string[];
// let numArr: number[];
// let boolArr: boolean[];
// strArr = ["Hello", "World"];
// numArr = [1, 2, 3];
// boolArr = [true, false];
var strArr;
var numArr;
var boolArr;
var strNumTuple;
strNumTuple = ["Hello", 4];
var myVoid = null;
var myVoid2 = undefined;
var myNull = undefined;
var myNull2 = null;
console.log(myString);
console.log(myNum);
console.log(myBool);
console.log(numArr);
